[default]
extend-ignore-re = ['/Fo\{\}']

[default.extend-identifiers]
IMPORT_OBJECT_NAME_EXPORTAS = "IMPORT_OBJECT_NAME_EXPORTAS"

[default.extend-words]
flate = "flate"
rela = "rela"
ot = "ot"
FRE = "FRE"
aranges = "aranges"

[files]
extend-exclude = ["external_test_suites", "wild/tests/bins"]
